server:
  port: 7399
  tomcat:
    max-http-form-post-size: -1

#关闭模板引擎的我缓存
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
  messages:
    basename: i18n.login


  mvc:
    static-path-pattern: /static/**
    format:
      date: yyyy-MM-dd
  datasource:
    username: root
    password: DST773344
    url: jdbc:mysql://localhost:33060/mybatis-plus?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.du.rems.entity
  mapper-locations: classpath:mapper/*.xml
