#server:
#  port: 7399
#  tomcat:
#    max-http-form-post-size: -1
##关闭模板引擎的我缓存
spring:
#  thymeleaf:
#    cache: false
#    servlet:
#      content-type: text/html
#  messages:
#    basename: i18n.login
  profiles:
    active: dev
#
#
##  mvc:
###    static-path-pattern: /static/**
##    format:
##     date: yyyy-MM-dd
#
#
#mybatis-plus:
#  type-aliases-package: com.du.rems.entity
#  mapper-locations: classpath:mapper/*.xml

server:
  port: 7399
  tomcat:
    max-http-form-post-size: -1
#关闭模板引擎的我缓存

