
new DataSourceConfig.
  Builder("jdbc:mysql://localhost:33060/rems","root","DST773344").build()
  .dbQuery(new MySqlQuery())
  .schema("mybatis-plus")
  .typeConvert(new MySqlTypeConvert())
  .keyWordsHandler(new MySqlKeyWordsHandler())
  .build();

new GlobalConfig.Builder()
  .fileOverride()
  .outputDir("/opt/baomidou")
  .author("baomidou")
  .enableKotlin()
  .enableSwagger()
  .dateType(DateType.TIME_PACK)
  .commentDate("yyyy-MM-dd")
  .build();

new PackageConfig.Builder()
  .parent("com.baomidou.mybatisplus.samples.generator")
  .moduleName("sys")
  .entity("po")
  .service("service")
  .serviceImpl("service.impl")
  .mapper("mapper")
  .mapperXml("mapper.xml")
  .controller("controller")
  .other("other")
  .pathInfo(Collections.singletonMap(OutputFile.mapperXml, "D://")
  .build();

new TemplateConfig.Builder()
  .disable(TemplateType.ENTITY)
  .entity("/templates/entity.java")
  .service("/templates/service.java")
  .serviceImpl("/templates/serviceImpl.java")
  .mapper("/templates/mapper.java")
  .mapperXml("/templates/mapper.xml")
  .controller("/templates/controller.java")
  .build();